import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { IntlProvider } from 'next-intl';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { [key: string]: any };
}>) {
  let i18n;
  try {
    i18n = require(`../i18n/${params.locale}.json`);
  } catch (error) {
    console.error(`Locale file not found.`);
    i18n = require(`../i18n/en.json`);
  }
  return (
    <html lang={params.locale ?? 'en'}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <IntlProvider messages={i18n} locale={params.locale ?? 'en'}>
          {children}
        </IntlProvider>
      </body>
    </html>
  );
}
