name: Audit

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js LTS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Check Node Vulnerabilities
      run: |
        npm install --package-lock-only --ignore-scripts --no-audit --save-prod
        npm audit --audit-level=moderate
