name: Update GitHub Project

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [opened, reopened, converted_to_draft, ready_for_review]

env:
  PROJECT_NUMBER: 6
  ISSUE_STATUSES: '{"priority-high": "Priority: High", "priority-medium": "Priority: Medium", "priority-low": "Priority: Low"}'
  PR_STATUS_DRAFT: 'In Progress'
  PR_STATUS_READY: 'In Progress'

permissions:
  pull-requests: write

jobs:
  update-project:
    name: Move project item
    runs-on: ubuntu-22.04
    steps:
      - uses: zowe-actions/shared-actions/project-move-item@main
        if: ${{ github.event.issue && fromJSON(env.ISSUE_STATUSES)[github.event.label.name] }}
        with:
          item-status: ${{ fromJSON(env.ISSUE_STATUSES)[github.event.label.name] }}
          project-number: ${{ env.PROJECT_NUMBER }}
          project-owner: zFernand0
          project-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: zowe-actions/shared-actions/project-move-item@main
        if: ${{ github.event.pull_request }}
        with:
          assign-author: true
          item-status: ${{ github.event.pull_request.draft && env.PR_STATUS_DRAFT || env.PR_STATUS_READY }}
          project-number: ${{ env.PROJECT_NUMBER }}
          project-owner: zFernand0
          project-token: ${{ secrets.GITHUB_TOKEN }}
